services:
  db:
    image: postgres:13.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: backend_test
      POSTGRES_PASSWORD: yourpassword  # Replace with a strong password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ruby:
    image: ruby:3.3.7-bullseye
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:yourpassword@db:5432/backend_test
      DB_HOST: db
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    command: bash -c "bundle config set path 'vendor/bundle' && bundle install --jobs=4 --retry=3 && bundle exec rails db:setup && bundle exec rspec"

    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: