version: 2.1

jobs:
  backend_unit_tests:
    docker:
      - image: ruby:3.3.7-bullseye
        environment:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:yourpassword@db:5432/backend_test
          DB_HOST: db
      - image: postgres:13.4
        name: db
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: backend_test
          POSTGRES_PASSWORD: yourpassword
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-backend-dependencies-{{ checksum "backend/Gemfile.lock" }}
            - v1-backend-dependencies-

      - run:
          name: Install System Dependencies
          command: |
            apt-get update
            apt-get install -y build-essential libpq-dev

      - run:
          name: Install Bundler
          command: gem install bundler

      - run:
          name: Install Gems
          command: |
            cd backend
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3

      - save_cache:
          paths:
            - backend/vendor/bundle
          key: v1-backend-dependencies-{{ checksum "backend/Gemfile.lock" }}

      - run:
          name: Setup Database
          command: |
            cd backend
            bundle exec rails db:setup

      - run:
          name: Run RSpec Tests
          command: |
            cd backend
            bundle exec rspec

  frontend_unit_tests:
    docker:
      - image: node:18
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-frontend-dependencies-{{ checksum "frontend/package-lock.json" }}
            - v1-frontend-dependencies-

      - run:
          name: Install Node.js Dependencies
          command: |
            cd frontend
            npm ci

      - save_cache:
          paths:
            - frontend/node_modules
          key: v1-frontend-dependencies-{{ checksum "frontend/package-lock.json" }}

      - run:
          name: Run Vitest Tests
          command: |
            cd frontend
            npx vitest

  e2e_tests:
    docker:
      - image: mcr.microsoft.com/playwright:latest
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-frontend-dependencies-{{ checksum "frontend/package-lock.json" }}
            - v1-frontend-dependencies-

      - run:
          name: Install Node.js Dependencies
          command: |
            cd frontend
            npm ci

      - save_cache:
          paths:
            - frontend/node_modules
          key: v1-frontend-dependencies-{{ checksum "frontend/package-lock.json" }}

      - run:
          name: Start Backend Server
          command: |
            cd backend
            rails server -p 3000 &

      - run:
          name: Start Playwright Tests
          command: |
            cd frontend
            npx playwright test spec/e2e

workflows:
  version: 2
  test:
    jobs:
      - backend_unit_tests
      - frontend_unit_tests
      - e2e_tests:
          requires:
            - backend_unit_tests
            - frontend_unit_tests