# .circleci/config.yml

jobs:
  vitest:
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd frontend && npm ci
      - run:
          name: Generate Nuxt files
          command: cd frontend && npx nuxi prepare
      - run:
          name: Run Vitest
          command: cd frontend && npx vitest spec/components

  playwright:
    docker:
      - image: ruby:3.3.0-slim-bullseye 
        environment:
          RAILS_ENV: test
      - image: cimg/node:18.18 
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update && apt-get install -y nodejs npm build-essential
            gem install bundler
      - run:
          name: Install Rails Gems
          command: cd backend && bundle install
      - run:
          name: Start Rails Backend
          command: cd backend && rails server -e test -p 3000
          background: true
      - run:
          name: Install Frontend Dependencies
          command: cd frontend && npm ci
      - run:
          name: Start Nuxt Frontend
          command: cd frontend && npx nuxi dev -p 3001
          background: true
      - run:
          name: Wait for Services to Start
          command: sleep 10
      - run:
          name: Run Playwright Tests
          command: cd frontend && npx playwright test spec/e2e

workflows:
  version: 2
  test_workflow:
    jobs:
      - playwright
