version: 2.1

jobs:
  test:
    docker:
      - image: ruby:3.3.7-bullseye
        environment:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:yourpassword@db:5432/backend_test
          DB_HOST: db
      - image: postgres:13.4
        name: db
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: backend_test
          POSTGRES_PASSWORD: yourpassword
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "backend/Gemfile.lock" }}
            - v1-dependencies-
      
      - run:
          name: Install System Dependencies
          command: |
            apt-get update
            apt-get install -y build-essential libpq-dev

      - run:
          name: Install Bundler
          command: gem install bundler

      - run:
          name: Install Gems
          command: |
            cd backend
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3

      - save_cache:
          paths:
            - backend/vendor/bundle
          key: v1-dependencies-{{ checksum "backend/Gemfile.lock" }}

      - run:
          name: Setup Database
          command: |
            cd backend
            bundle exec rails db:setup

      - run:
          name: Run RSpec Tests
          command: |
            cd backend
            bundle exec rspec

workflows:
  version: 2
  test:
    jobs:
      - test
