version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - run:
          name: Navigate to frontend directory
          command: cd frontend
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run Vitest
          command: npx vitest spec/components

workflows:
  version: 2
  test_workflow:
    jobs:
      - test
